# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llama_ready_pb2 as llama__ready__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llama_ready_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitConnection = channel.unary_unary(
                '/ShardService/InitConnection',
                request_serializer=llama__ready__pb2.InitRequest.SerializeToString,
                response_deserializer=llama__ready__pb2.InitResponse.FromString,
                _registered_method=True)
        self.PrefillStep = channel.unary_unary(
                '/ShardService/PrefillStep',
                request_serializer=llama__ready__pb2.PrefillRequest.SerializeToString,
                response_deserializer=llama__ready__pb2.PrefillResponse.FromString,
                _registered_method=True)
        self.DecodeStep = channel.unary_unary(
                '/ShardService/DecodeStep',
                request_serializer=llama__ready__pb2.DecodeRequest.SerializeToString,
                response_deserializer=llama__ready__pb2.DecodeResponse.FromString,
                _registered_method=True)


class ShardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrefillStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecodeStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.InitConnection,
                    request_deserializer=llama__ready__pb2.InitRequest.FromString,
                    response_serializer=llama__ready__pb2.InitResponse.SerializeToString,
            ),
            'PrefillStep': grpc.unary_unary_rpc_method_handler(
                    servicer.PrefillStep,
                    request_deserializer=llama__ready__pb2.PrefillRequest.FromString,
                    response_serializer=llama__ready__pb2.PrefillResponse.SerializeToString,
            ),
            'DecodeStep': grpc.unary_unary_rpc_method_handler(
                    servicer.DecodeStep,
                    request_deserializer=llama__ready__pb2.DecodeRequest.FromString,
                    response_serializer=llama__ready__pb2.DecodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ShardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShardService/InitConnection',
            llama__ready__pb2.InitRequest.SerializeToString,
            llama__ready__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrefillStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShardService/PrefillStep',
            llama__ready__pb2.PrefillRequest.SerializeToString,
            llama__ready__pb2.PrefillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecodeStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShardService/DecodeStep',
            llama__ready__pb2.DecodeRequest.SerializeToString,
            llama__ready__pb2.DecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
