# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llama_ready.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llama_ready.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llama_ready.proto\"@\n\nTensorData\x12\x14\n\x0ctensor_bytes\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"\xa9\x01\n\rRuntimeConfig\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x13\n\x0blayer_split\x18\x02 \x01(\x05\x12\x13\n\x0btorch_dtype\x18\x03 \x01(\t\x12\x16\n\x0emax_new_tokens\x18\x04 \x01(\x05\x12\x11\n\tdo_sample\x18\x05 \x01(\x08\x12\x13\n\x0btemperature\x18\x06 \x01(\x02\x12\r\n\x05top_p\x18\x07 \x01(\x02\x12\r\n\x05top_k\x18\x08 \x01(\x05\"-\n\x0bInitRequest\x12\x1e\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x0e.RuntimeConfig\"/\n\x0cInitResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"u\n\x0ePrefillRequest\x12\x1b\n\x06hidden\x18\x01 \x01(\x0b\x32\x0b.TensorData\x12#\n\x0e\x61ttention_mask\x18\x02 \x01(\x0b\x32\x0b.TensorData\x12!\n\x0cposition_ids\x18\x03 \x01(\x0b\x32\x0b.TensorData\"b\n\x0fPrefillResponse\x12\x1f\n\nnext_token\x18\x01 \x01(\x0b\x32\x0b.TensorData\x12\x16\n\x0eserver_infer_s\x18\x02 \x01(\x01\x12\x16\n\x0eserver_total_s\x18\x03 \x01(\x01\",\n\rDecodeRequest\x12\x1b\n\x06hidden\x18\x01 \x01(\x0b\x32\x0b.TensorData\"a\n\x0e\x44\x65\x63odeResponse\x12\x1f\n\nnext_token\x18\x01 \x01(\x0b\x32\x0b.TensorData\x12\x16\n\x0eserver_infer_s\x18\x02 \x01(\x01\x12\x16\n\x0eserver_total_s\x18\x03 \x01(\x01\x32\x9e\x01\n\x0cShardService\x12-\n\x0eInitConnection\x12\x0c.InitRequest\x1a\r.InitResponse\x12\x30\n\x0bPrefillStep\x12\x0f.PrefillRequest\x1a\x10.PrefillResponse\x12-\n\nDecodeStep\x12\x0e.DecodeRequest\x1a\x0f.DecodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llama_ready_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORDATA']._serialized_start=21
  _globals['_TENSORDATA']._serialized_end=85
  _globals['_RUNTIMECONFIG']._serialized_start=88
  _globals['_RUNTIMECONFIG']._serialized_end=257
  _globals['_INITREQUEST']._serialized_start=259
  _globals['_INITREQUEST']._serialized_end=304
  _globals['_INITRESPONSE']._serialized_start=306
  _globals['_INITRESPONSE']._serialized_end=353
  _globals['_PREFILLREQUEST']._serialized_start=355
  _globals['_PREFILLREQUEST']._serialized_end=472
  _globals['_PREFILLRESPONSE']._serialized_start=474
  _globals['_PREFILLRESPONSE']._serialized_end=572
  _globals['_DECODEREQUEST']._serialized_start=574
  _globals['_DECODEREQUEST']._serialized_end=618
  _globals['_DECODERESPONSE']._serialized_start=620
  _globals['_DECODERESPONSE']._serialized_end=717
  _globals['_SHARDSERVICE']._serialized_start=720
  _globals['_SHARDSERVICE']._serialized_end=878
# @@protoc_insertion_point(module_scope)
